BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "mes_ricevuti" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"id_mitt"	INTEGER NOT NULL,
	"text"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "mes_inviati" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"id_dest"	INTEGER NOT NULL,
	"text"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "Contatti" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Nome"	TEXT NOT NULL,
	"Cognome"	TEXT NOT NULL,
	"Bloccato"	TEXT NOT NULL,
	PRIMARY KEY("id")
);
COMMIT;
